// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Odisea.Modules.Booking.Infrastructure;

#nullable disable

namespace Odisea.Modules.Booking.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("booking_ref_seq");

            modelBuilder.Entity("Odisea.Modules.Booking.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("AgentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_user_id");

                    b.Property<string>("BreakdownJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown_json");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("check_in");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("check_out");

                    b.Property<decimal?>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DepartureId")
                        .HasColumnType("uuid")
                        .HasColumnName("departure_id");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hotel_name");

                    b.Property<decimal?>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<string>("OfferToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("offer_token");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("program_name");

                    b.Property<string>("ProviderBookingRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_booking_ref");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider_code");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ref");

                    b.Property<decimal?>("SellAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sell_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("Ref")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_ref");

                    b.HasIndex("AgencyId", "CreatedAt")
                        .HasDatabaseName("ix_bookings_agency_id_created_at");

                    b.ToTable("bookings", "booking");
                });

            modelBuilder.Entity("Odisea.Modules.Booking.Domain.BookingPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsLead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lead");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_booking_passengers");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_passengers_booking_id");

                    b.ToTable("booking_passengers", "booking");
                });

            modelBuilder.Entity("Odisea.Modules.Booking.Domain.BookingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_booking_status_history");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_status_history_booking_id");

                    b.ToTable("booking_status_history", "booking");
                });

            modelBuilder.Entity("Odisea.Modules.Booking.Domain.BookingPassenger", b =>
                {
                    b.HasOne("Odisea.Modules.Booking.Domain.Booking", null)
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_passengers_bookings_booking_id");
                });

            modelBuilder.Entity("Odisea.Modules.Booking.Domain.BookingStatusHistory", b =>
                {
                    b.HasOne("Odisea.Modules.Booking.Domain.Booking", null)
                        .WithMany("History")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_status_history_bookings_booking_id");
                });

            modelBuilder.Entity("Odisea.Modules.Booking.Domain.Booking", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
