// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Odisea.Modules.Catalog.Infrastructure;

#nullable disable

namespace Odisea.Modules.Catalog.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261008224613_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_destinations");

                    b.HasIndex("Name", "Country")
                        .IsUnique()
                        .HasDatabaseName("ix_destinations_name_country");

                    b.ToTable("destinations", "catalog");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.HasKey("Id")
                        .HasName("pk_hotels");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_hotels_destination_id");

                    b.ToTable("hotels", "catalog");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.HotelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalHotelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_hotel_code");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider_code");

                    b.HasKey("Id")
                        .HasName("pk_hotel_mappings");

                    b.HasIndex("HotelId", "ProviderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_hotel_mappings_hotel_id_provider_code");

                    b.HasIndex("ProviderCode", "ExternalHotelCode")
                        .IsUnique()
                        .HasDatabaseName("ix_hotel_mappings_provider_code_external_hotel_code");

                    b.ToTable("hotel_mappings", "catalog");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.LocationMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<string>("ExternalLocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_location_code");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider_code");

                    b.HasKey("Id")
                        .HasName("pk_location_mappings");

                    b.HasIndex("DestinationId", "ProviderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_location_mappings_destination_id_provider_code");

                    b.HasIndex("ProviderCode", "ExternalLocationCode")
                        .IsUnique()
                        .HasDatabaseName("ix_location_mappings_provider_code_external_location_code");

                    b.ToTable("location_mappings", "catalog");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider_code");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("season");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_programs");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_programs_destination_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_programs_status");

                    b.ToTable("programs", "catalog");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.ProgramDeparture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("TransportNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("transport_note");

                    b.HasKey("Id")
                        .HasName("pk_program_departures");

                    b.HasIndex("ProgramId", "StartDate")
                        .HasDatabaseName("ix_program_departures_program_id_start_date");

                    b.ToTable("program_departures", "catalog");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.ProgramHotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.HasKey("Id")
                        .HasName("pk_program_hotels");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_program_hotels_hotel_id");

                    b.HasIndex("ProgramId", "HotelId")
                        .IsUnique()
                        .HasDatabaseName("ix_program_hotels_program_id_hotel_id");

                    b.ToTable("program_hotels", "catalog");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.Hotel", b =>
                {
                    b.HasOne("Odisea.Modules.Catalog.Domain.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotels_destinations_destination_id");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.HotelMapping", b =>
                {
                    b.HasOne("Odisea.Modules.Catalog.Domain.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotel_mappings_hotels_hotel_id");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.LocationMapping", b =>
                {
                    b.HasOne("Odisea.Modules.Catalog.Domain.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_location_mappings_destinations_destination_id");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.Program", b =>
                {
                    b.HasOne("Odisea.Modules.Catalog.Domain.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_programs_destinations_destination_id");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.ProgramDeparture", b =>
                {
                    b.HasOne("Odisea.Modules.Catalog.Domain.Program", null)
                        .WithMany("Departures")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_departures_programs_program_id");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.ProgramHotel", b =>
                {
                    b.HasOne("Odisea.Modules.Catalog.Domain.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_hotels_hotels_hotel_id");

                    b.HasOne("Odisea.Modules.Catalog.Domain.Program", null)
                        .WithMany("Hotels")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_hotels_programs_program_id");
                });

            modelBuilder.Entity("Odisea.Modules.Catalog.Domain.Program", b =>
                {
                    b.Navigation("Departures");

                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
