<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Odisea.SharedKernel\Odisea.SharedKernel.csproj" />
    <ProjectReference Include="..\Modules\Odisea.Modules.Agencies\Odisea.Modules.Agencies.csproj" />
    <ProjectReference Include="..\Modules\Odisea.Modules.Catalog\Odisea.Modules.Catalog.csproj" />
    <ProjectReference Include="..\Modules\Odisea.Modules.Pricing\Odisea.Modules.Pricing.csproj" />
    <ProjectReference Include="..\Modules\Odisea.Modules.Booking\Odisea.Modules.Booking.csproj" />
    <ProjectReference Include="..\Modules\Odisea.Modules.Integrations\Odisea.Modules.Integrations.csproj" />
  </ItemGroup>
</Project>
